<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DDT SM-LOG Negative</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>12f486b0-4763-44f3-92cd-8af7ef72d7fc</testSuiteGuid>
   <testCaseLink>
      <guid>60036e35-358a-474c-bd11-418f6adb6292</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <iterationNameVariable>
         <defaultValue>''</defaultValue>
         <description></description>
         <id>5fbba2ba-2f1a-423b-9589-abed8e1a1ac4</id>
         <masked>false</masked>
         <name>var_email</name>
      </iterationNameVariable>
      <testCaseId>Test Cases/Mobile/SM-Login/SM-LOG (DDT Negative)</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>52f4b2d7-0599-43d8-8d72-66938032aff6</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Test Data Negative</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>52f4b2d7-0599-43d8-8d72-66938032aff6</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>email</value>
         <variableId>5fbba2ba-2f1a-423b-9589-abed8e1a1ac4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>52f4b2d7-0599-43d8-8d72-66938032aff6</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>de1e5848-c017-42c3-959b-018878fbe6b6</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
