<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Indomaret</name>
   <tag></tag>
   <elementGuidId>3c0b47fe-6511-47f4-ae75-1e7b6e924441</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='application']/div/div/div[8]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div:nth-of-type(8) > a.list</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fe400d80-fe3b-4c8d-88fb-64fc6fac3353</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>211dc545-c2de-4aaa-b180-21428a58cb5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>list-item</value>
      <webElementGuid>3de6d47e-8f88-440a-a5e1-c88fad43ab81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#/indomaret</value>
      <webElementGuid>3e4f7786-4c06-4efa-b06d-a9d333f8b992</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Indomaret</value>
      <webElementGuid>aef915cc-d9d1-400f-ae5f-3cb48f79310b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application&quot;)/div[@class=&quot;page-container scroll&quot;]/div[@class=&quot;payment-container-list&quot;]/div[8]/a[@class=&quot;list&quot;]</value>
      <webElementGuid>39606947-3a8a-4a63-93da-be29dd9a5d2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Web - Flow Beli Event/SW-BE06/Page_Coding.ID - Cart/iframe_concat(id(, , snap-midtrans, , ))_po_da1ce1</value>
      <webElementGuid>f2e95aaa-e593-4650-9c87-6915e88e4264</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='application']/div/div/div[8]/a</value>
      <webElementGuid>5484afae-430d-44ec-ad2e-da11edccb6e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Danamon Online Banking'])[1]/following::a[1]</value>
      <webElementGuid>da2185a6-8978-444c-8885-2182c491de2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OCTO Clicks'])[1]/following::a[2]</value>
      <webElementGuid>1b7b8b4d-418c-4b07-8b60-cbe6c3bf3201</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Akulaku PayLater'])[1]/preceding::a[1]</value>
      <webElementGuid>4e1d0095-d682-43e1-93c9-4d281bc6d623</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#/indomaret')]</value>
      <webElementGuid>210cffd4-46f4-4ca4-b2f2-6f534b7e3a3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/a</value>
      <webElementGuid>7058acff-8ddf-4588-8be9-0bc0b9856710</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#/indomaret' and (text() = 'Indomaret' or . = 'Indomaret')]</value>
      <webElementGuid>c4b356b6-4de4-48f5-b9a1-847455ad1664</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
