<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_ShopeePay</name>
   <tag></tag>
   <elementGuidId>535ed9c6-53af-4160-a415-53011a33a983</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='application']/div/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.title-text.text-actionable-bold</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b190053d-4e80-43a9-83f2-18e588d78a3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title-text text-actionable-bold</value>
      <webElementGuid>072f568c-c451-48cc-8dd0-c06ab8454e9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ShopeePay</value>
      <webElementGuid>88ada490-8f0e-4bff-bb34-59a9e0bbc11d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application&quot;)/div[@class=&quot;page-container scroll&quot;]/div[@class=&quot;page-title&quot;]/span[@class=&quot;title-text text-actionable-bold&quot;]</value>
      <webElementGuid>f187d33b-e92d-4462-84b0-a27a29959d0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Web - Flow Beli Event/SW-BE02/Page_Coding.ID - Cart/iframe_concat(id(, , snap-midtrans, , ))_po_742cc3</value>
      <webElementGuid>a158f70d-9eac-4302-ae74-775869046d82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='application']/div/div/span</value>
      <webElementGuid>c438cf23-788c-45c9-b6f5-74d8d961e995</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order details'])[1]/following::span[1]</value>
      <webElementGuid>50a5854f-4cc3-4ab5-841c-4eaff333840d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='How to pay'])[1]/preceding::span[2]</value>
      <webElementGuid>dbb976a1-80cd-4ce5-b85b-f77001e44b45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ShopeePay']/parent::*</value>
      <webElementGuid>bff4b131-5108-4eeb-bdf8-57ffdbab30d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/span</value>
      <webElementGuid>6de74938-3427-4387-8ddc-a8ecfc9dc3d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'ShopeePay' or . = 'ShopeePay')]</value>
      <webElementGuid>62d5897d-51d7-4b74-bc1d-95b1c76468a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
