<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_OCTO Clicks</name>
   <tag></tag>
   <elementGuidId>f7ad112a-96cf-4934-9ed6-c47eb3aa2195</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='application']/div/div/div[6]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div:nth-of-type(6) > a.list</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>22d9c655-50d6-41ef-b2f5-b92580f22703</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>499225c4-67d1-4d89-901e-bc80ae911f58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>list-item</value>
      <webElementGuid>752549a1-73bc-4345-a64d-0d697a2b37e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#/octo-clicks</value>
      <webElementGuid>52e95ffd-6118-4608-ade4-0afe0722c4e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OCTO Clicks</value>
      <webElementGuid>d83f5ea4-a5ed-414f-ba16-a8d41f3a1348</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application&quot;)/div[@class=&quot;page-container scroll&quot;]/div[@class=&quot;payment-container-list&quot;]/div[6]/a[@class=&quot;list&quot;]</value>
      <webElementGuid>8fbe7dd4-3905-405a-af45-144ba00d1de9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Web - Flow Beli Event/SW-BE04/Page_Coding.ID - Cart/iframe_concat(id(, , snap-midtrans, , ))_po_355136</value>
      <webElementGuid>eceadf5b-41f6-44c5-9235-da2b51962c24</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='application']/div/div/div[6]/a</value>
      <webElementGuid>f039dfac-40b3-4ef4-8d6b-79befeef04b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BCA KlikPay'])[1]/following::a[1]</value>
      <webElementGuid>7f238d88-2b01-43ad-9762-733dc6d1918c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ShopeePay'])[1]/following::a[2]</value>
      <webElementGuid>ddf7a84e-1d2f-498c-a9f7-15fee990e0f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Danamon Online Banking'])[1]/preceding::a[1]</value>
      <webElementGuid>0e265d56-6731-4839-98d9-ac8878b19ee4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#/octo-clicks')]</value>
      <webElementGuid>ee8a88f3-3996-4f6f-bd23-c8e541e57b8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/a</value>
      <webElementGuid>12661604-d203-4442-b2b0-2b1a9ff0425f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#/octo-clicks' and (text() = 'OCTO Clicks' or . = 'OCTO Clicks')]</value>
      <webElementGuid>dc13a9aa-ebb8-41ff-b0ac-01b7e8a43917</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
