<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Pendaftaran Ditutup</name>
   <tag></tag>
   <elementGuidId>a3996fa1-3626-4a60-8bbb-508f9aa081d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='demo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#demo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8d7d7748-fc53-4b48-b8a0-fd6f99de2fe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>demo</value>
      <webElementGuid>404c2749-e5e6-4213-ab2f-3c25b30ede88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pendaftaran Ditutup</value>
      <webElementGuid>5e3c3625-5e74-4809-bedb-ccee9a9e1c76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;demo&quot;)</value>
      <webElementGuid>c0259cb6-62dd-4391-9f83-49873a02801d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='demo']</value>
      <webElementGuid>b27faaf6-18e3-41bd-b054-8731e5639d2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zoom'])[1]/following::span[1]</value>
      <webElementGuid>298399c7-2762-4110-8838-7645cb6328a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Event lain yang banyak diminati'])[1]/preceding::span[1]</value>
      <webElementGuid>12316d0f-4366-4600-8c11-81136d1e9b4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Day 3: Predict using Machine Learning'])[1]/preceding::span[1]</value>
      <webElementGuid>7f7641cd-a4b7-4185-a3f4-7b5bb05d8d06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pendaftaran Ditutup']/parent::*</value>
      <webElementGuid>62fb744e-6e25-4684-9670-257681179057</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/span</value>
      <webElementGuid>282a57cc-c739-44c9-98c9-286b5ae25f7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'demo' and (text() = 'Pendaftaran Ditutup' or . = 'Pendaftaran Ditutup')]</value>
      <webElementGuid>3841b05b-856a-42fc-9ca1-f4027d94b414</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
